POST http://localhost:9008/SV5/ItemsTable/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}