POST http://localhost:9008/V5/BillsTable/Insert/AsIsAndTS
Content-Type: application/json

{
  "BuyerName": "16",
  "BuyerAddress": "",
  "BuyerGST": "",
  "InvoiceNo": "",
  "InvoiceDate": "",
  "InvoiceStateCode": ""
}