POST http://localhost:9008/V5/ItemsTable/AddWithDefault/AddFromDefaultObj
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}