POST http://localhost:9008/SV5/BillsTable/AddWithDefault/AddFromDefaultObj
Content-Type: application/json

{
  "BuyerName": "",
  "BuyerAddress": "",
  "BuyerGST": "",
  "InvoiceNo": "",
  "InvoiceDate": "",
  "InvoiceStateCode": ""
}