POST http://localhost:9008/V5/ItemsTable/SubTableOnObj/Insert/AsIs/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}