POST http://localhost:9008/V5/ItemsTable/SubTableOnArray/Alter/WithPk/{RowPk}/{KeyName}/{pk}
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}