POST http://localhost:9008/V5/ItemsTable/Insert/ColumnExist
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}