POST http://localhost:9008/V6/ItemsTable/Alter/WithPk/{pk}
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}