POST http://localhost:9009/SV7/BillsTable/Insert/AsIsAndTS
Content-Type: application/json

{
  "BuyerName": "",
  "BuyerAddress": "",
  "BuyerGST": "",
  "InvoiceNo": "",
  "InvoiceDate": "",
  "InvoiceStateCode": ""
}
